package cn.atsoft.dasheng.erp.enums;

public enum ViewTypeEnum {
    ORDER_TYPE,ORDER_STATUS,ORDER_BY_CREATE_USER,ORDER_BY_DETAIL,ORDER_LOG,ORDER_LOG_DETAIL,SPU_CLASS,STOREHOUSE,TYPE,SKU_COUNT,NUM_COUNT
}
