package cn.atsoft.dasheng.message.enmu;

public enum MicroServiceType {
    CONTRACT, PRODUCTION_PLAN,WORK_ORDER,PRODUCTION_TASK,PRODUCTION_PICKLISTS,QUALITY_TASK,INSTOCKORDER,OUTSTOCKORDER
    ,Announcements,MAINTENANCE,DYNAMIC,INSTOCK_VIEW_EXCEL,OUTSTOCK_VIEW_EXCEL,INIT,SKU_NUMBER,STOCK_DETAIL,SKU_PRICE
}
