#Oracle配置
#spring:
#  datasource:
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCLCDB
#    username: GUNS
#    password: GUNS
#    filters: wall,mergeStat

#SQLServer配置
#spring:
#  datasource:
#    driverClassName: net.sourceforge.jtds.jdbc.Driver
#    url: jdbc:jtds:sqlserver://127.0.0.1:3433;DatabaseName=guns
#    username: guns
#    password: 123456
#    filters: wall,mergeStat

#PostgreSQL配置
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/guns
#    username: postgres
#    password: 123456
#    filters: wall,mergeStat

# Mysql数据库
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root
#    filters: wall,mergeStat

# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.239/daoxin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: daoxin
    password: 123qweasd
    filters: wall,mergeStat
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.2.239/hh-local?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: hh-local
#    password: CprNCmi2DDCzztWW
#    filters: wall,mergeStat

    # 连接池大小根据实际情况调整
    max-active: 20
    max-pool-prepared-statement-per-connection-size: 20

  redis:
    host: 192.168.2.244
    password: 123qweasd

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.qq.com
    port: 587
    username: sn93@qq.com
    password: xxxpassword

  rabbitmq:
    addresses: 192.168.2.245
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
    prefix: jazz123

# 邮件发送（改为自己的账号）
mail:
  from: sn93@qq.com

freed-template:
  customer:
    add: "[操作人]添加客户"
    edit: "[操作人]修改客户"
    delete: "[操作人]删除了客户"
  Crmbusiness:
    add: "[操作人]添加商机"
    edit: "[操作人]修改商机"
    delete: "[操作人]删除了商机"
  Contacts:
    add: "[操作人]添加联系人"
    edit: "[操作人]修改联系人"
    delete: "[操作人]删除了联系人"
  Adress:
    add: "[操作人]添加了地址"
    edit: "[操作人]修改了地址"
    delete: "[操作人]删除了地址"
  Contract:
    add: "[操作人]添加了合同"
    edit: "[操作人]修改了合同"
    delete: "[操作人]删除了合同"
  ErpOrder:
    add: "[操作人]添加了订单"
    edit: "[操作人]修改了订单"
    delete: "[操作人]删除了订单"
  Repair:
    add: "[操作人]添加了售后"
    edit: "[操作人]修改了售后"
    delete: "[操作人]删除了售后"
  TrackMessage:
    add: "[操作人]添加了跟进"

# 微信相关配置
wx:
  # 小程序相关配置
  miniapp:
    appid: wx4e0e2e89ad2e48ef
    secret: fe7c079bea0fe0836ad23a7a865db9d4
    aesKey: 3333
    token: 11111
    msg-data-format: JSON

  mp:
    appId: wx6b94599d68b93b0f
    secret: 623b049c5bad1bba929b055bdd4862f0
    token: 11111
    aesKey: 3333


#  # 小程序相关配置
#miniapp:
#  appid: wx4e0e2e89ad2e48ef
#  secret: fe7c079bea0fe0836ad23a7a865db9d4
#  aesKey: 3333
#  token: 11111
#  msg-data-format: JSON
# 支付相关配置
pay:
  notifyUrl: https://dasheng-soft.picp.vip

  # 微信支付 小程序用
  weiXinMiNiPay:
    appId: 111
    mchId: 222
    mchKey: 3333

# 推送支付信息,生产环境如开启支付功能 应设置为 true
pushPayInfo: false

aliyun:
  accessId: LTAI5tRtx3bPozdsUhbF6PS1
  accessKey: h7yO2s07LOseh8OONvDpJgPwHcBtIn

  Sms:
    SignName: 工业服务网
    templateCode: SMS_137360127
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: hunts-cnc
    callbackUrl: https://dasheng-soft.picp.vip/v1
    path: upload/
  oss2:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: hunts-file
    callbackUrl: https://dasheng-soft.picp.vip/v1
    path: upload/
wxcp:
  corpId: ww4d053c3a7cebff09
  secret: T_z92-En8k2u-zeJeuK1GYoIPqSA_OnewujNFi8EY_U
  agentId: 1000002
  token: OqrSyeq2MbOfvzNpaf2nq
  aesKey: POS55bE1u1TB9ziYlVPRcbrUCgp54kw5su2XatSPGSh

#手机端跳转路径
mobile:
  url: http://192.168.2.111:3000/
  apiUrl: http://192.168.2.100:80

templateId: 3WLJEyiwiby2y4STpyuFXsTdTdM9ste9mAbUQBzT